server:
  port: 9090
spring:
  datasource:

#    sqlServer
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.18.63:1433;databaseName=UPLOAD;trustServerCertificate=true
    username: sa
    password: Root1234
    hikari:
#      max-lifetime: 50000
      #最小空闲连接数
      minimum-idle: 10
      # 连接池最大连接数，默认是10
      maximum-pool-size: 60

#
#  mvc:
#    path match:
#      matching-strategy: ant_path_matcher



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  executor-type: batch




